# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazun', models.CharField(help_text=b'The magazun', max_length=255, verbose_name='The Magazun')),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(help_text=b'This marka', max_length=255, verbose_name='Question marka')),
            ],
        ),
        migrations.CreateModel(
            name='Modeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeli', models.CharField(help_text=b'modeli', max_length=255, verbose_name='the modeli')),
                ('conect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(help_text=b'country of orign', max_length=255, verbose_name='country of origin')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(help_text=b'The Producer', max_length=255, verbose_name='The Producer')),
            ],
        ),
        migrations.CreateModel(
            name='TupZap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tupzap', models.CharField(help_text=b'tupzap', max_length=255, verbose_name='tup zapchastun')),
            ],
        ),
        migrations.AddField(
            model_name='magazun',
            name='conect1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Marka'),
        ),
        migrations.AddField(
            model_name='magazun',
            name='conect2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Modeli'),
        ),
        migrations.AddField(
            model_name='magazun',
            name='conect3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TupZap'),
        ),
        migrations.AddField(
            model_name='magazun',
            name='conect4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Nation'),
        ),
        migrations.AddField(
            model_name='magazun',
            name='conect5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Producer'),
        ),
    ]
